pipeline {
    agent any

    environment {

        PYTHON_HOME = '/path/to/your/python/Users/katerynagoncharova/Hillel_course/pythonProject/hillel_honcharova/Lesson_31/Hillel_project.py

    stages {
        stage('Checkout') {
            steps {

                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {

                script {
                    sh '''
                        ${PYTHON_HOME}/bin/pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {

                script {
                    sh '''
                        ${PYTHON_HOME}/bin/python -m unittest discover
                    '''
                }
            }
        }

        stage('Publish Test Results') {
            steps {

                junit '**/test-*.xml'
            }
        }
    }

    post {
        always {
            // Надсилання електронної пошти з результатами тестування
            emailext (
                to: 'InsertYour@Mail.Here',
                subject: "Jenkins Build ${currentBuild.currentResult}: ${currentBuild.fullDisplayName}",
                body: "Результати тестування:\n\n${currentBuild.fullDisplayName}\n\n${currentBuild.currentResult}",
                attachLog: true
            )
        }
    }
}